// export file file yang mau diperlihatkan ke luar
// export {default as NamaMethod/Variable} from "./path-to-file"
export {default as Kemahasiswaan} from "./data/kemahasiswaan.json"
export {default as Blanko} from "./data/blanko.json"
export {default as PendaftaranVerifikasi} from "./data/pendaftaran-verifikasi.json"
export {default as Pembayaran} from "./data/pembayaran.json"
export {default as Pengumuman} from "./data/pengumuman.json"
export {default as PelayananAdministratif} from "./data/pelayanan-administratif.json"
export {default as ProsesAkademik} from "./data/proses-akademik.json"
export {default as WisudaYudisium} from "./data/wisuda-yudisium.json"
export {default as HeroSection} from "./sections/HeroSection"
export {default as BlankoSection} from "./sections/BlankoSection"
export {default as AlurKemahasiswaanCarousel} from "./components/AlurKemahasiswaanCarousel"
export {default as BlankoCarousel} from "./components/BlankoCarousel"
export {default as ContentRenderer} from "./components/ContentRenderer"
export type {ContentBlock} from "./types";